philips-software/amp-hal-st

.github/workflows/ci.yml

The seanmiddleditch/gha-setup-ninja action has not yet moved from node12 to node16 as is recommended by GitHub (https://github.com/seanmiddleditch/gha-setup-ninja/issues/16). This gives unnecessary warnings in our build summaries.
Replace the usage of the action by installing ninja via the package manager.

build: remove seanmiddleditch/gha-setup-ninja

---

CMakeLists.txt
examples/blink/CMakeLists.txt
examples/freertos/CMakeLists.txt
hal_st/middlewares/STM32_WPAN/CMakeLists.txt
hal_st/middlewares/ble_middleware/CMakeLists.txt

build: refactor CMakeLists files to use emil_build_for instead of conditionally adding targets

build: refactor CMakeLists files to use emil_build_for

---

.github/workflows/linting-formatting.yml
CMakeLists.txt
hal_st/middlewares/ble_middleware/GapPeripheralSt.cpp
hal_st/middlewares/ble_middleware/GapPeripheralSt.hpp

Fix to return ConstByteRange that only contains data instead of the entire data structure of advertisementData and scanresponseData (infra::BoundedVector).

fix GetAdvertisementData and GetScanResponseData in GapPeripheralSt

---

hal_st/middlewares/ble_middleware/GapCentralSt.cpp
hal_st/middlewares/ble_middleware/GapPeripheralSt.cpp
hal_st/middlewares/ble_middleware/GapSt.cpp
hal_st/middlewares/ble_middleware/GapSt.hpp

A requested transition from Standby to Advertise to Standby from the product would stay in Advertise state

fix: incorrect connection handle in state transitions

---

hal_st/middlewares/ble_middleware/GattServerSt.cpp
hal_st/middlewares/ble_middleware/GattServerSt.hpp

An anomaly from GATT client is observed with few mobile phone where GATT server changed indication sent to GATT server even if not subscribed. If the indication is not confirmed then it results in GATT procedure timeout. Added confirm indication to avoid GATT procedure timeout.

fix: add confirmation for gatt indication

---

hal_st/stm32fxxx/UartStm.cpp
hal_st/stm32fxxx/UartStm.hpp
hal_st/stm32fxxx/UartStmDma.cpp
hal_st/stm32fxxx/UartStmDma.hpp
hal_st/stm32fxxx/UartStmDuplexDma.cpp
hal_st/stm32fxxx/UartStmDuplexDma.hpp

Add UART pin swapping option for supported devices.
Using feature testing via known defines we can add an optional configuration option to optionally swap the Tx and Rx pins.
This is an advanced feature of the UART peripherals of the WB, G0, G4 and F7 series.

feat: add uart pin swap configuration option when supported

---

hal_st/stm32fxxx/GeneratePinoutTableStructure.xsl

Newer families are relying on a more generic IP database. 
This could lead to generated code with non-existing pins and peripherals for some part numbers.

fix: use mcu database to filter non-existing pin

---

hal_st/default_init/DefaultInit.cpp

Weak makes it possible to override which is useful for library integration in different contexts.

chore: Make abort a weak definition

---

hal_st/stm32fxxx/I2cStm.cpp
hal_st/stm32fxxx/I2cStm.hpp

Extend hal_st to support I2C on new family STM32WBA5xx using the development board with STM32WBA52CG.
I tested only in the STM32WBA52CG. For the other families, considering the necessary changes, I'm assuming the build is enough to validate compatibility.
The modification is not really relevant, but this time is useful to validate in the new MCU and check the other datasheets over for the best way to test features instead of families.

feat: Extend I2C for stm32wba family

---

hal_st/stm32fxxx/UsbLinkLayerStm.cpp
hal_st/stm32fxxx/UsbLinkLayerStm.hpp

As implementation is for USB OTG FS, avoid building it for microcontrollers with USB but without OTG FS.

chore: use less generic define for usb driver

---

hal_st/stm32fxxx/AdcDmaStm.cpp
hal_st/stm32fxxx/AnalogToDigitalPinStm.cpp
hal_st/stm32fxxx/AnalogToDigitalPinStm.hpp
hal_st/stm32fxxx/CMakeLists.txt
hal_st/stm32fxxx/PeripheralTableWbaxx.xml

Extend hal_st to support ADC and TIMER for new family STM32WBA5xx.
This PR depends on #327

feat: add ADC and timer for mcu stm32wbaxx

---

hal_st/stm32fxxx/CMakeLists.txt
hal_st/stm32fxxx/DefaultClockNucleoWBA52CG.cpp
hal_st/stm32fxxx/SpiMasterStm.cpp
hal_st/stm32fxxx/SpiMasterStm.hpp
hal_st/stm32fxxx/SpiMasterStmDma.cpp
hal_st/stm32fxxx/SpiMasterStmDma.hpp
hal_st/synchronous_stm32fxxx/SynchronousSpiMasterStm.cpp
hal_st/synchronous_stm32fxxx/SynchronousSpiMasterStm.hpp

Extend hal_st to support SPI for new family STM32WBA5xx.
* The SPI Master with DMA was tested with WBA52, WB55 and F767.
* Only implement the Master mode.

feat: add SPI master for mcu stm32wba

---

examples/helloworld/Main.cpp
hal_st/instantiations/NucleoUi.hpp
hal_st/stm32fxxx/GpioStm.cpp
hal_st/stm32fxxx/GpioStm.hpp

Align available `hal::Port::` ports to the actual ports available for the selected chip.

feat: make hal::Port's contents depend on actual available ports

---

hal_st/stm32fxxx/DmaStm.cpp

Fix handling multi byte transfer and proper peripheral transmit size for GPDMA instances.
Additionally add support for a second GPDMA instance when available.

fix: handling GPDMA multi byte transfer

---

hal_st/stm32fxxx/FlashInternalStm.cpp
hal_st/stm32fxxx/FlashInternalStm.hpp
hal_st/synchronous_stm32fxxx/SynchronousFlashInternalStm.cpp
hal_st/synchronous_stm32fxxx/SynchronousFlashInternalStm.hpp

Extend hal_st to support internal flash for new family STM32WBA5xx.
* Tested both synchronous and asynchronous implementation.
* Created a separated solution after a sync with Richard to isolate this specific solution for memory of 128 bits.

feat: add internal flash for mcu stm32wba 

---

hal_st/stm32fxxx/AnalogToDigitalPinStm.cpp
hal_st/stm32fxxx/AnalogToDigitalPinStm.hpp

During the battery test on RCM, it was noticed an assert issue inside HAL_ST command for family STM32WB.
The prescaler assert is different between the families, reason to have a family macro oriented as a solution.

fix: prescaler for ADC

---

hal_st/stm32fxxx/SpiMasterStmDma.cpp

According to the WBA manual, the **SPI_CR1_CSTART** has to be set after the **SPI_CR1_SPE** to enable the SPI with DMA since the first starts the master transfer while the second enables the peripheral. 
In other words, it was starting the transmission with the peripheral disabled.
The solution consists in reorder them.
OBS:
The **SPI_CR1_CSTART** is a command for WBA family only (until now).

fix: command sequence for flash spi with dma

---

CMakePresets.json
hal_st/stm32fxxx/CMakeLists.txt
hal_st/stm32fxxx/DefaultClockNucleoG474xxx.cpp
hal_st/stm32fxxx/DefaultClockNucleoG474xxx.hpp
hal_st/stm32fxxx/PeripheralTableGxxx.xml
hal_st/stm32fxxx/mcu/STM32G474V(B-C-E)Tx.xml

note: no QUADSPI and FMC support, yet
- QUADSPI IRQ is generated as `QUADSPI1_IRQn`, but it seems ST has dropped the `1` for these (new?) peripherals and the correct IRQn now is `QUADSPI_IRQn`.
- The FMC peripherals are different in terms of supported devices compared to already supported ST chips. This new peripheral doesn't support SDRAM. Thus the used/generated typedef is wrong. This needs to be looked in to.

feat: add support for STM32G474VxT

---

st/hal_driver.cmake

This adds a dependency on the linker to provide symbols that we don't provide. Adding this define ensures __cmsis_start is never generated.

feat: prevent the CMSIS drivers from providing __cmsis_start function

---

hal_st/stm32fxxx/GpioStm.cpp

Within a MCU family, a MCU can have more or less ports defined
This is fixed by using the same approach as #350

fix: gpio clock not enabled

---

hal_st/stm32fxxx/AnalogToDigitalPinStm.cpp

Also remove the fixed size allocation and let the compiler decide the required size.
C-style array is used because type deduction using `std::array` is not possible for all MCUs.

feat: add support for ADC channel 19

---

hal_st/stm32fxxx/UartStm.hpp
hal_st/stm32fxxx/UartStmDma.hpp

Remove the duplicated struct definition to support including both classes in same .cpp

chore: remove duplicated lpuart struct

---

hal_st/stm32fxxx/DmaStm.cpp
hal_st/stm32fxxx/DmaStm.hpp

The current linked list implementation uses a single local memory for all eight DMA channels. The fix creates a separate memory space for each channel. The linked list will now only be used when circular mode is requested. 
To reduce memory allocation, both control registers were removed from memory.

fix: circular mode for wba family

---

hal_st/stm32fxxx/CMakeLists.txt

This PR enables the `UartStmDuplexDma` class for STM32H5 series.
Additionally, work with cmake lists instead of a concatenation of `if` clauses.

feat: include UartStmDuplexDma in STM32H5 series build

---

hal_st/stm32fxxx/PeripheralTableH5xx.xml
hal_st/stm32fxxx/PinoutTableItems.xml

This introduces minimal FDCAN support that generates the relevant peripheral and pinout tables.

Introduce FDCAN peripheral generation

---

CMakeLists.txt
hal_st/stm32fxxx/GpioStm.cpp
hal_st/stm32fxxx/GpioStm.hpp

This change allows the user of the InterruptEnable function to choose betweeen a dispatched or immediate handling of the pin interrupt.
Removed a double dispatch. The pin change was handled using a DispatchInterruptHandler. And in the ExitInterrupt, which was handled on the EventDispatch, the actual action would be dispatched, again.

feat: extend gpio interrupt interface to enable immediate interrupt handlers

---

hal_st/stm32fxxx/UartStm.cpp
hal_st/stm32fxxx/UartStm.hpp
hal_st/stm32fxxx/UartStmDma.cpp
hal_st/stm32fxxx/UartStmDma.hpp
hal_st/stm32fxxx/UartStmDuplexDma.cpp
hal_st/stm32fxxx/UartStmDuplexDma.hpp

There seems to be a lot of duplication with different flavour of UART's. This PR aims to reuse UartStm base class and build on top of it for DMA functionality.

refactor: UartStmDuplexDma to reuse UartStm

---

hal_st/cortex/InterruptCortex.cpp
hal_st/stm32fxxx/CMakeLists.txt
hal_st/stm32fxxx/DefaultClockDiscoveryH573I.cpp
hal_st/stm32fxxx/DefaultClockNucleoH563ZI.cpp
hal_st/stm32fxxx/FlashInternalHighCycleAreaStm.cpp
hal_st/stm32fxxx/FlashInternalHighCycleAreaStm.hpp
hal_st/stm32fxxx/FlashInternalStm.cpp
hal_st/stm32fxxx/FlashInternalStm.hpp
hal_st/stm32fxxx/FlashInternalStmDetail.hpp

This PR cleans up code for writing data to internal flash (see PR #437).
It fixes writing data larger than 16 bytes for STM32WBA/STM32H5 families.
The STM32H5 provides an internal "high cycle area" flash, that allows higher endurance than the user main memory.
Special attention is needed for its usage (no single byte access, NMI handling for unwritten data, ...).
This implementation has been tested in combination with `services::CyclicStore` and `services::FlashRegion` and complies with the basic assumptions on the `hal::Flash` interface.

feat: support for internal high cycle area flash

---

hal_st/synchronous_stm32fxxx/SynchronousFlashInternalStm.cpp
hal_st/synchronous_stm32fxxx/SynchronousUartStm.cpp

- Fix RX UART interrupt not being enabled
- Fix write to flash for larger payloads
- Fix flash erase for dual bank

fix: sync uart and flash for wba

---

hal_st/cortex/InterruptCortex.cpp

When the NMI interrupt was enabled, allow it to be disabled.

feat: allow disable NonMaskableInt_IRQn interrupt

---

hal_st/stm32fxxx/CMakeLists.txt

Add missing `services.util` dependency that is needed by usage of `services::FlashAlign`.

fix: add missing cmake dependency

---

.github/workflows/ci.yml
.github/workflows/social-interaction.yml
.gitignore
CMakeLists.txt
CMakePresets.json
integration_test/runner/CMakeLists.txt
integration_test/runner/Hooks.cpp
integration_test/runner/Main.cpp
integration_test/runner/StepsGpio.cpp
integration_test/runner/StepsUart.cpp
integration_test/runner/Waiting.cpp
integration_test/runner/Waiting.hpp

ci: add windows build from amp-devcontainer-cpp

feat: update to latest main of amp-cucumber-cpp-runner

---

hal_st/stm32fxxx/AnalogToDigitalPinStm.cpp
hal_st/stm32fxxx/GpioStm.cpp
hal_st/stm32fxxx/GpioStm.hpp

This PR adds support for usage of internal ADC channels by allowing to manually define a AnalogPin channel value.
Additionally, this adds ADC IRQ lookup for `STM32H5` series.

feat: add support for internal ADC channels

---

hal_st/stm32fxxx/AdcDmaMultiChannelStm.cpp
hal_st/stm32fxxx/AdcDmaMultiChannelStm.hpp
hal_st/stm32fxxx/AdcTimerTriggeredBase.cpp
hal_st/stm32fxxx/AdcTimerTriggeredBase.hpp
hal_st/stm32fxxx/AnalogToDigitalPinStm.hpp
hal_st/stm32fxxx/CMakeLists.txt

Provide channel-specific conversion configuration for the `AdcDmaMultiChannelStm`.
Configuration will look like this:
```cpp
hal::AdcDmaMultiChannelStm<2> multiChannel(adc, receiveStream, 
hal::AdcPinConfig{positivePin, ADC_SAMPLETIME_47CYCLES_5, true},
hal::AdcPinConfig{ADC_CHANNEL_TEMPSENSOR, ADC_SAMPLETIME_47CYCLES_5});
```
Additionally add support for timer-triggered ADC conversion.

feat: provide channel-specific conversion configuration and timer-triggered support

---

hal_st/stm32fxxx/DmaStm.cpp

For aborting a continuous GPDMA transfer with a circular buffering or a double buffering, the software can abort, on its own, a still active channel with the following sequence:
1. Suspend the channel
2. Wait until it was effectively supended
3. Reset the channel (which will reset the EN bit)
Ignoring this sequence can cause the channel not being able to start again when an DMA transfer was active while setting the RESET bit.

fix: GPDMA channel abort sequence

---

hal_st/stm32fxxx/DmaStm.cpp

This commit breaks downstream. Not sure of the root cause yet, but reverting to unblock use of halst main downstream.
This reverts commit dad8a32c74b204e25049cac42612125aea9bef99

fix: revert "fix: GPDMA channel abort sequence (#555)"

---

hal_st/stm32fxxx/CMakeLists.txt
hal_st/stm32fxxx/EthernetMacH5xxStm.cpp
hal_st/stm32fxxx/EthernetMacStm.hpp
hal_st/stm32fxxx/EthernetSmiStm.cpp
hal_st/stm32fxxx/PeripheralTableH5xx.xml
hal_st_lwip/instantiations_lwip/CMakeLists.txt

This adds Ethernet MAC and MDIO support for the STM32H5 family.
Since the Ethernet DMA registers differ significantly it was decided the MAC implementation is done in its own source file.

feat: add Ethernet support for STM32H5 family

---

hal_st/stm32fxxx/EthernetSmiStm.cpp
hal_st/stm32fxxx/EthernetSmiStm.hpp

If the PHY is not able to perform Auto-Negotiation,
select the SpeedLink based on the Control Register

feat: evaluate PHY Auto-Negotiation ability

---

hal_st/middlewares/ble_middleware/GapCentralSt.cpp
hal_st/middlewares/ble_middleware/GapCentralSt.hpp
hal_st/middlewares/ble_middleware/GapSt.cpp
hal_st/middlewares/ble_middleware/GapSt.hpp
hal_st/middlewares/ble_middleware/TracingGapCentralSt.cpp

ST Centrals support 'not supported' 'mandatory' and 'optional' secureConnectionSupport levels.
This PR aims to add the 'not supported' mode.

feat: Extend GapCentralST's SetSecurityMode

---

hal_st/synchronous_stm32fxxx/SynchronousHardwareSemaphoreStm.cpp
hal_st/synchronous_stm32fxxx/SynchronousHardwareSemaphoreStm.hpp
hal_st/synchronous_stm32fxxx/SynchronousSynchronizedRandomDataGeneratorStm.cpp
hal_st/synchronous_stm32fxxx/SynchronousSynchronizedRandomDataGeneratorStm.hpp

Fixes: #605 
On the WB55 the HSI48 oscillator is used by the RNG peripheral and USB. When currently using the RNG on CPU1, the HSI48 will be disabled, causing any active USB connection to drop as well. This PR modifies the RNG implementation to match the CPU2 behavior:
> The RNG peripheral access requires getting Sem0. In addition, the CPU2 makes one attempt to get Sem5. If this is successful, it switches ON the HSI48 oscillator and configures the 48 MHz clock selection of the RNG IP to be HSI48. This assumes the RCC is configured to feed the RNG IP with a 48 MHz clock and not either LSI or LSE. In the latter case, the previous step is done anyway even though not relevant and the RNG operates on the selected clock. When Sem5 is busy, the CPU2 does not change anything in the RNG clock …

fix: the HSI48 oscillator is disabled by the random number generator

---

hal_st/stm32fxxx/SystemTickTimerService.cpp
hal_st/stm32fxxx/SystemTickTimerService.hpp

After clock reconfiguration it is necessary to reset the SysTick timer to take the current SystemCoreClock into account.

feat: allow resetting the SysTick timer

---

hal_st/stm32fxxx/EthernetMacH5xxStm.cpp
hal_st/stm32fxxx/EthernetSmiStm.cpp

This improves the STM32H5 ethernet support by moving the RMII configuration to the SMI layer and resetting the ETH and MAC registers in the destructor of the MAC layer class.

chore: STM32H5 ethernet improvements

---

hal_st/stm32fxxx/EthernetSmiStm.cpp

On link down, the MAC layer (typically) resets all ETH and MAC registers, including the MII clock range configuration. Fix this by configuring the clock range after calling link down.

fix: MII clock range after link down

---

CMakeLists.txt
hal_st/middlewares/ble_middleware/GattClientSt.cpp
hal_st/middlewares/ble_middleware/GattClientSt.hpp
hal_st/middlewares/ble_middleware/TracingGattClientSt.cpp
hal_st/middlewares/ble_middleware/TracingGattClientSt.hpp

Fix to retry when WriteWithoutResponse return an error due to insufficient resources in the stack.
https://github.com/philips-software/amp-embedded-infra-lib/pull/930

fix: implement retry mechanism for Gatt WriteWithoutResponse
